name: Build LVGL Docs PDF

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'LVGL branch/tag (e.g. v9.4, v9.3, master)'
        required: true
        default: 'v9.4'

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout LVGL
        uses: actions/checkout@v4
        with:
          repository: lvgl/lvgl
          ref: ${{ inputs.ref }}
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # NOTE:
      # - texlive-full is large and slow but painless.
      # - If it times out, switch to the "slim toolchain" below and add missing packages as errors indicate.
      - name: Install LaTeX toolchain (texlive-full)
        run: |
          sudo apt-get update
          sudo apt-get install -y make latexmk texlive-full

      # --- Slim toolchain alternative (commented out) ---
      # - name: Install LaTeX toolchain (slim)
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y make latexmk \
      #       texlive-latex-extra texlive-fonts-recommended texlive-lang-cjk
      # ---------------------------------------------------

      - name: Install Python deps
        working-directory: docs
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # Fallback common deps; adjust if your docs use extra Sphinx extensions
            pip install sphinx sphinx-rtd-theme
          fi

      - name: Build PDF (Sphinx LaTeX)
        working-directory: docs
        run: |
          # Try Makefile first
          if [ -f Makefile ]; then
            make latexpdf
          else
            # Generic fallback
            sphinx-build -b latex . _build/latex
            latexmk -pdf -silent -cd _build/latex/*.tex
          fi

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: lvgl-docs-pdf-${{ inputs.ref }}
          path: |
            docs/_build/latex/*.pdf
          if-no-files-found: error
